version: 0.2
phases:
  install:
    runtime-versions:
       python: 3.13
  pre_build:
    commands:
      - python3 --version
      - pip3 install --upgrade pip
      - pip3 install --upgrade awscli
      - sudo docker info
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - ls
      - docker build -t cf-demo:1 .
      - docker container ls
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - aws ecr get-login-password --region ca-central-1 | docker login --username AWS --password-stdin 234130772191.dkr.ecr.ca-central-1.amazonaws.com
      - docker tag cf-demo:1 234130772191.dkr.ecr.ca-central-1.amazonaws.com/cf-demo:1
      - docker push 234130772191.dkr.ecr.ca-central-1.amazonaws.com/cf-demo:1
